### ISSUE TITLE
can't build validator-keys 

### ISSUE THREAD

**Issue by ne1000** [ripple/validator-keys-tool#18] opened 2020-09-26 13:44 UTC
Compile error report on ubuntu16.04

```
 In file included from /tmp/validator-keys-tool/src/ValidatorKeys.cpp:21:
/tmp/validator-keys-tool/src/ValidatorKeys.h:21:10: fatal error: ripple/crypto/KeyType.h: No such file or directory
 #include <ripple/crypto/KeyType.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/validator-keys.dir/build.make:62: recipe for target 'CMakeFiles/validator-keys.dir/src/ValidatorKeys.cpp.o' failed
make[2]: *** [CMakeFiles/validator-keys.dir/src/ValidatorKeys.cpp.o] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/validator-keys.dir/all' failed
make[1]: *** [CMakeFiles/validator-keys.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ximinez** [comment] 2020-09-28 22:01
We're working on getting that issue fixed as we speak. The next version, 0.3.2 (https://github.com/ripple/validator-keys-tool/pull/19), should fix all these errors once it's merged. You can build the candidate branch now if you'd like.

In the meantime, there is a workaround described at https://github.com/ripple/validator-keys-tool/issues/15#issuecomment-649712129, which can be used with the current 0.3.0 version in `master` and `release`.

**Comment by ximinez** [comment] 2020-09-29 18:10
We just pushed 0.3.2, which should resolve the current build issues. I'm going to close this issue. If you have further questions or problems, please feel free to reopen this issue or open a new one. Thanks for your feedback!

**Closed by ximinez** 2020-09-29 18:10 UTC

**Comment by ne1000** [comment] 2020-10-02 01:43
@ximinez hi, I still unable to build it.
```
[100%] Building CXX object CMakeFiles/validator-keys.dir/src/test/ValidatorKeysTool_test.cpp.o
[100%] Linking CXX executable validator-keys
/root/boost_1_71_0/boost/regex/v4/cpp_regex_traits.hpp:966: error: undefined reference to 'boost::re_detail_107100::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
/root/boost_1_71_0/boost/regex/v4/cpp_regex_traits.hpp:962: error: undefined reference to 'boost::re_detail_107100::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
collect2: error: ld returned 1 exit status
CMakeFiles/validator-keys.dir/build.make:144: recipe for target 'validator-keys' failed
make[2]: *** [validator-keys] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/validator-keys.dir/all' failed
make[1]: *** [CMakeFiles/validator-keys.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ximinez** [comment] 2020-10-02 14:49
From the path in that blurb, it looks like you're building with Boost version 1.71.0. I can confirm that the build fails with 1.71 on my end, too.

Can you try installing Boost 1.70 and building with that? If so, we'll know what to target in the next version.

**Comment by ximinez** [comment] 2020-10-02 15:22
Woops! I missed something!

Before you try Boost 1.70, try deleting your `.nih_c` directory and rebuilding from scratch. I neglected that step the first time when I switched Boost versions. After I did that, the build worked perfectly.
